### ISSUE TITLE
use gpuR

### ISSUE THREAD

**Issue by gdlc** [QuantGen/BGData#45]
For computations of G matrices gpuR can give use better performance that the current multi-core approach. I suggest to add a function crossprods_gpu(), see template below.

Problems to consider:
     - Will we require gpuR? For now, while we test it and learn, we may not require gpuR
     - Detecting whether  gpu is availalbe, if not throw an error.
     - Modifying getG by adding an argument useGPU, if TRUE, we call crossprods_gpu, that authomatically will override, nCores.

Gustavo

crossprods_gpu <- function(x, y = NULL, use_tcrossprod = FALSE) { #*# remove some args
    dx <- dim(x)
    if (!is.null(y)) {
        y <- as.matrix(y)
        dy <- dim(y)
        if (use_tcrossprod) {
            if (dx[2L] != ncol(y)) {
                stop("Error in tcrossprod_gpu: non-conformable arguments.")
            }
        } else {
            if (dx[1L] != dy[1L]) {
                stop("Error in crossprod_gpu: non-conformable arguments.")
            }
        }
    }
    
    x <- gpuMatrix(x,"float")
    if (!is.null(y)) {
        y <- gpuMatrix(y,"float")
    }
    if (use_tcrossprod) {
       Xy <- tcrossprod(x, y)
    } else {
    	Xy <- crossprod(x, y)
    }
    
    return(Xy)
}

**Comment by agrueneberg** [comment]
This was added in ad563fbf2e89358acde572fc4be618b6bac3ac99. The `gpuR` package can only be suggested instead of depended on, as compilation will fail in environments where neither CUDA nor OpenCL is available.
