### ISSUE TITLE
Error in .local(.Object, ...) : No such device

### ISSUE THREAD

**Issue by kayhan-batmanghelich** [QuantGen/BGData#46]
Hi,

I am getting this error and cannot figure out why it is happening:

```
Extracting number of samples and rownames from FAM file...
Extracting number of variants and colnames from BIM file...
Error in .local(.Object, ...) : No such device
```

obviously, it can find the `fam` and `bim` and the `bed` file is there too but I don't see why I get this error. I would be thankful if you could help.

Thanks,
Kayhan

**Comment by agrueneberg** [comment]
Hi Kayhan,

I am not sure what to make out of "No such device" in this context. Is the .bed file in an unusual location (different file system, different host, ...)? What operating system are you running, and what is your version of R and Rcpp (`packageVersion("Rcpp")`)?

Thanks,
Alex

**Comment by kayhan-batmanghelich** [comment]
Hi Alex,

The version of R is 3.4.1 . The version of Rcpp is:

```
> packageVersion("Rcpp")
[1] ‘0.12.14’
```
and yes the files are in usual places:
```
-rw-r--r-- 1 batmangh mc560kp      76630 Aug  9 23:47 CG10kAaHg19Clean_v2_Mar2013.fam
-rw-r--r-- 1 batmangh mc560kp   19731078 Aug  9 23:47 CG10kAaHg19Clean_v2_Mar2013.bim
-rw-r--r-- 1 batmangh mc560kp  564562353 Aug  9 23:47 CG10kAaHg19Clean_v2_Mar2013.bed
```

```
> m = BEDMatrix('CG10kNhwHg19Clean_v2_Mar2013.bed')
Extracting number of samples and rownames from FAM file...
Extracting number of variants and colnames from BIM file...
Error in .local(.Object, ...) : No such device
```

the operating system:
```
[batmangh@br005 Genetics]$ uname -a
Linux br005.pvt.bridges.psc.edu 3.10.0-514.26.2.el7.x86_64 #1 SMP Tue Jul 4 15:04:05 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by agrueneberg** [comment]
Hi Kayhan,

thanks, I don't see anything unusual... Maybe your file system does not support memory mapping? Please check the `Type` column of the `df -T CG10kAaHg19Clean_v2_Mar2013.bed` output.

Thanks,
Alex

**Comment by kayhan-batmanghelich** [comment]
Thanks Alex,

This is the output:
```
batmangh@br005 Genetics]$ df -T CG10kAaHg19Clean_v2_Mar2013.bed
Filesystem     Type     1K-blocks          Used    Available Use% Mounted on
/pghbio        fuse 2418185650176 1926487998336 491697651840  80% /pghbio
```

I don't know that it supports memory mapping or not. Please let me know.

Best,
Kayhan

**Comment by kayhan-batmanghelich** [comment]
@agrueneberg yep, that was the file system issue. I moved the data to a different file system and it worked:
```
[batmangh@br005 ~]$ df -T CG10kAaHg19Clean_v2_Mar2013.bed
Filesystem                          Type  1K-blocks       Used  Available Use% Mounted on
br001.opa.bridges.psc.edu:/nfs/home nfs4 6440364032 4195274752 2245089280  66% /home
```

What file systems are compatible with the code? Obviously `nfs4` is.

Thanks,
Kayhan

**Comment by agrueneberg** [comment]
Hi Kayhan,

what file systems are compatible is an excellent question. My impression was all of them, because I wasn't aware of this issue. You're probably running ZFS behind FUSE, and ZFS should work because we're using that too in combination with NFS. So I guess it has something to do with FUSE? Unfortunately, I don't know enough about those file systems and your system configuration to find an answer to this question, but maybe your sysadmins can give some guidance? All we're doing is basically `mmap()`.

Cheers,
Alex
