### ISSUE TITLE
write.plink?

### ISSUE THREAD

**Issue by nevrome** [QuantGen/BGData#52]
Thanks for implementing this package!

Is there already a workflow to write merged or subset data back to the file system in plink binary format?

**Comment by agrueneberg** [comment]
Hi Clemens,

we think that this task is better left to PLINK. For subsetting, take a look at `--keep` or `--remove` for samples and `--extract` or `--exclude` for variants. For merging, there is `--merge-list`.

Cheers,
Alex

**Comment by nevrome** [comment]
Alright - thanks for the fast reply!

I would like to go for a pure R workflow one day without any system dependencies, but in that case good old `system()` will have to do the job a little longer. 

Best,
Clemens

**Comment by agrueneberg** [comment]
You might be interested in the `write_bed` function of the BGLR package then. Your matrix needs to fit into memory and it only writes a .bed file, i.e., you need to generate the .bim and .fam files manually to get a full PLINK fileset.
The `snp_writeBed` function of the bigsnpr package looks also promising, but I haven't tried it yet.

Cheers,
Alex

**Comment by nevrome** [comment]
Ah - thanks for these hints. To my understanding both these packages rely on loading the data fully into memory and I wonder if this can be avoided for merging and subsetting. Your approach looks very promising in that regard.

Independent of this specific application bigsnpr is pretty interesting. Thanks for making me aware!
