### ISSUE TITLE
  'mc.cores' > 1 is not supported on Windows

### ISSUE THREAD

**Issue by kerrypettigrew** [QuantGen/BGData#56]
I'm running RStudio on windows and have hit an error at the Summarizing Data step:

> ### Summarising data
> # Use chunkedApply to count missing values (among others):
> countNAs <- chunkedApply(X = geno(bg), MARGIN = 2, FUN = function(x) sum(is.na(x)))
Error in mclapply(X = seq_len(nChunks), FUN = chunkApply, ..., mc.cores = nCores) : 
  'mc.cores' > 1 is not supported on Windows

**Comment by agrueneberg** [comment]
Please set `nCores` to 1, parallelism is not supported on Windows.
